### ISSUE TITLE
Line number will overflow when it exceeds 255

### ISSUE THREAD

**Issue by chc69** [edgexfoundry/device-gpio#97]
Hi 

I am using the device-gpio of EdgeX v2.3. I am aware the GPIO line number of the device profile will overflow when the line number exceeds 255. 
I am using Dell 3001 gateway, assigned external GPIO from line #330 to #338. This will be truncated into 74 since the original variable type of line is Uint8.

**Comment by cloudxxx8** [comment]
fixed by #98
